steps:
  # Step 1: Install curl and unzip, then download Nexus shared library
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >
        set -e

        apt-get update

        apt-get install -y curl unzip

        cd /workspace

        curl -u <NEXUS_USERNAME>:<NEXUS_PASSWORD> -L -o shared-lib.zip \
        https://<NEXUS_URL>/repository/maven-shared-lib/com/fact/1.1.0/fact-1.1.0-lib.zip

        unzip -o shared-lib.zip

        echo "Listing workspace contents:"
        ls -ltr /workspace
    entrypoint: bash

  # Step 2: Run your Groovy orchestrator
  - name: us-central1-docker.pkg.dev/devops-446301/my-docker-repo/groovy-builder-image
    args:
      - '-c'
      - |
        cd /workspace/groovy-lib-main
        groovy scripts/main.groovy

        echo "---- Artifact Content ----"
        cat build/demo-build.txt
    entrypoint: bash

options:
  logging: CLOUD_LOGGING_ONLY
