steps:
  # Build ZIP
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
  
  # Deploy ZIP directly
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mvn deploy:deploy-file \
          -DgroupId=com.example \
          -DartifactId=jenkins-shared-lib \
          -Dversion=3.1.1 \
          -Dpackaging=zip \
          -Dfile=target/jenkins-shared-lib-3.1.1.zip \
          -DrepositoryId=maven-nexus-lib \
          -Durl=http://35.222.195.140:8081/repository/maven-nexus-lib/ \
          -Dusername=nexus3_creds \
          -Dpassword=$$NEXUS3_CREDS
    secretEnv: ['NEXUS3_CREDS']
----

- name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/ramtruely/nexus-shared-library.git', '.']
