steps:
  # Step 1: Download ZIP from Nexus
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "Downloading ZIP from Nexus..."
        curl -u "$NEXUS_USER:$NEXUS_PASS" \
          -o downloaded.zip \
          "https://your-nexus-url/repository/your-repo/path/to/file.zip"

          curl -u USER:PASSWORD -O $(curl -s -u USER:PASSWORD "https://nexus360.system.us.sbc:8081/nexus/maven_n3/com/fact/sbc/na/shared-lib/1.1.0/" | grep -oP 'gcp-shared-lib-1\.1\.0-[^"]+\.zip' | sort | tail -1 | sed 's|^|https://nexus360.system.us.sbc:8081/nexus/maven_n3/com/fact/sbc/na/shared-lib/1.1.0/|')


  # Step 2: Extract the ZIP
  - name: 'gcr.io/cloud-builders/unzip'
    args:
      - "downloaded.zip"
      - "-d"
      - "extracted"

  # Step 3: Display extracted files (optional)
  - name: 'gcr.io/cloud-builders/bash'
    script: |
      echo "Extracted files:"
      ls -R extracted

---

steps:
  - name: gcr.io/cloud-builders/bash
    script: |
      echo "Downloading & extracting ZIP from Nexus in one step..."

      curl -u "$NEXUS_USER:$NEXUS_PASS" \
        -o file.zip \
        "https://your-nexus-url/repository/your-repo/path/to/file.zip"

      unzip file.zip -d extracted

      echo "Contents after extract:"
      ls -R extracted

      
---
import java.util.zip.ZipFile

// --- Download ---
def url = "https://nexus.example.com/shared-lib.zip"
def creds = System.getenv("NEXUS_CREDS")
def conn = new URL(url).openConnection()
conn.setRequestProperty("Authorization", creds)
new File("shared-lib.zip").bytes = conn.inputStream.bytes

// --- Unzip ---
new ZipFile("shared-lib.zip").entries().each { e ->
    def f = new File(e.name)
    if (e.isDirectory()) f.mkdirs()
    else { f.parentFile.mkdirs(); f.bytes = new ZipFile("shared-lib.zip").getInputStream(e).bytes }
}

// --- Auto-load all vars files ---
def engine = new GroovyScriptEngine(["shared-lib/workspace/vars"] as String[])

// --- Auto-run all public methods in each vars file ---
new File("shared-lib/workspace/vars").listFiles().each { file ->
    def script = engine.run(file.name, [])
    script.metaClass.methods.each { m ->
        if (m.modifiers == 1 && m.name != "main") {
            println "Running ${file.name} -> ${m.name}()"
            script."${m.name}"()
        }
    }
}
